# .stack-analyzer.yml - Tech Stack Analyzer Configuration

# Files and directories to exclude from scanning
exclude:
  # Exclude all rule YAML files to avoid detecting them as project technologies
  - "internal/rules/core/**/*.yaml"
  - "internal/rules/core/**/*.yml"
