package scanner

import (
	"path/filepath"
	"sort"
	"strings"
	"unicode/utf8"

	enry "github.com/go-enry/go-enry/v2"
)

const (
	// largeProgrammingFileThreshold is the minimum byte size for a programming
	// file to be flagged as potentially vendored or bundled (e.g. minified JS).
	largeProgrammingFileThreshold = 500 * 1024 // 500 KB

	// minGeneratedFilesForObservation is the minimum number of generated/vendored
	// files in a directory before it is reported.
	minGeneratedFilesForObservation = 5

	// topDirsToShow is the maximum number of directories shown per observation.
	topDirsToShow = 5
)

// dirCount tracks per-directory file counts for a single signal type.
type dirCount struct {
	counts map[string]int // top-level relative dir → count
	total  int
}

func newDirCount() *dirCount {
	return &dirCount{counts: make(map[string]int)}
}

func (d *dirCount) add(relPath string) {
	d.total++
	dir := topDir(relPath)
	d.counts[dir]++
}

// dirAtDepth returns the directory prefix of a scan-root-relative path at the given depth.
// E.g. depth=1: "frontend/app/src/main.ts" → "frontend"
//
//	depth=2: "frontend/app/src/main.ts" → "frontend/app"
//	depth=1: "main.go" → "(root)"
func dirAtDepth(relPath string, depth int) string {
	clean := strings.TrimPrefix(filepath.ToSlash(relPath), "/")
	parts := strings.SplitN(clean, "/", depth+1)
	if len(parts) <= 1 || (len(parts) == 2 && parts[0] == "") {
		return "(root)"
	}
	if len(parts) <= depth {
		return strings.Join(parts[:len(parts)-1], "/")
	}
	return strings.Join(parts[:depth], "/")
}

// topDir returns the depth-2 directory prefix of a scan-root-relative path.
// Using depth-2 gives more actionable grouping than depth-1 for large monorepos.
func topDir(relPath string) string {
	return dirAtDepth(relPath, 2)
}

// DirObservation is an actionable observation grouped by directory.
type DirObservation struct {
	// Total is the total number of flagged files across all directories.
	Total int
	// TopDirs lists the directories with the most flagged files, sorted descending.
	TopDirs []DirEntry
}

// DirEntry is a single directory with its flagged file count.
type DirEntry struct {
	Dir   string
	Count int
}

// ScanObservations holds all file-level observations collected during a scan.
// Only populated when an ObservationCollector is attached to the scanner.
type ScanObservations struct {
	Generated  *DirObservation // files identified as generated by go-enry
	Vendored   *DirObservation // files identified as vendored by go-enry
	LargeFiles *DirObservation // programming files exceeding the size threshold
	NonUTF8    int             // total count of non-UTF-8 files
}

// ObservationCollector accumulates file-level signals during a scan.
// Attach one to the scanner before calling Scan(); retrieve results via Build().
//
// It is safe to use only from the scanner's single-threaded recurse/processFile
// call chain — no synchronisation is needed.
type ObservationCollector struct {
	basePath  string
	generated *dirCount
	vendored  *dirCount
	large     *dirCount
	nonUTF8   int
}

// NewObservationCollector creates a collector rooted at basePath.
// basePath is the scan root; it is used to derive relative paths for grouping.
func NewObservationCollector(basePath string) *ObservationCollector {
	return &ObservationCollector{
		basePath:  filepath.Clean(basePath),
		generated: newDirCount(),
		vendored:  newDirCount(),
		large:     newDirCount(),
	}
}

// Observe is called once per file during scanning.
//
//   - absPath: absolute file path
//   - content: file bytes (already read by processFile)
//   - langType: go-enry language type ("programming", "data", "markup", "prose", "")
func (c *ObservationCollector) Observe(absPath string, content []byte, langType string) {
	rel := c.relPath(absPath)

	if enry.IsGenerated(rel, content) {
		c.generated.add(rel)
	}
	if enry.IsVendor(rel) && !isDotDir(rel) {
		c.vendored.add(rel)
	}
	if langType == "programming" && len(content) >= largeProgrammingFileThreshold {
		c.large.add(rel)
	}
	if !utf8.Valid(content) {
		c.nonUTF8++
	}
}

// Build compiles the collected signals into ScanObservations.
// Call this once after Scan() has completed.
func (c *ObservationCollector) Build() *ScanObservations {
	return &ScanObservations{
		Generated:  buildDirObservation(c.generated),
		Vendored:   buildDirObservation(c.vendored),
		LargeFiles: buildDirObservation(c.large),
		NonUTF8:    c.nonUTF8,
	}
}

func (c *ObservationCollector) relPath(absPath string) string {
	rel, err := filepath.Rel(c.basePath, absPath)
	if err != nil {
		return filepath.Base(absPath)
	}
	return filepath.ToSlash(rel)
}

func buildDirObservation(dc *dirCount) *DirObservation {
	if dc.total == 0 {
		return nil
	}
	entries := make([]DirEntry, 0, len(dc.counts))
	for dir, count := range dc.counts {
		if count >= minGeneratedFilesForObservation {
			entries = append(entries, DirEntry{Dir: dir, Count: count})
		}
	}
	sort.Slice(entries, func(i, j int) bool {
		if entries[i].Count != entries[j].Count {
			return entries[i].Count > entries[j].Count
		}
		return entries[i].Dir < entries[j].Dir
	})
	if len(entries) > topDirsToShow {
		entries = entries[:topDirsToShow]
	}
	return &DirObservation{Total: dc.total, TopDirs: entries}
}

// isDotDir returns true if the relative path starts with a dot-directory
// (e.g. ".github/", ".vscode/"). These are project tooling, not vendored
// code, even though go-enry's IsVendor flags them for language stats purposes.
func isDotDir(relPath string) bool {
	clean := strings.TrimPrefix(relPath, "/")
	return len(clean) > 0 && clean[0] == '.'
}

// LargeFileThreshold returns the configured large file size threshold in bytes.
// Exposed for use by the formatting layer in cmd.
func LargeFileThreshold() int {
	return largeProgrammingFileThreshold
}
