tech: mkdocs
name: MkDocs
dependencies:
  - type: pypi
    name: mkdocs
    example: mkdocs
  - type: docker
    name: squidfunk/mkdocs-material
    example: squidfunk/mkdocs-material
files:
  - mkdocs.yml
