package parsers

import (
	"testing"

	"github.com/petrarca/tech-stack-analyzer/internal/types"
)

const pubspecLockFixture = `# Generated by pub
packages:
  http:
    dependency: "direct main"
    description:
      name: http
      url: "https://pub.dev"
    source: hosted
    version: "1.2.0"
  meta:
    dependency: transitive
    source: hosted
    version: "1.11.0"
  test:
    dependency: "direct dev"
    source: hosted
    version: "1.24.9"
sdks:
  dart: ">=3.0.0 <4.0.0"
`

func TestDartParser_ParsePubspecLock(t *testing.T) {
	p := NewDartParser()
	deps := p.ParsePubspecLock(pubspecLockFixture)

	byName := map[string]types.Dependency{}
	for _, d := range deps {
		byName[d.Name] = d
	}
	if byName["http"].Version != "1.2.0" || byName["http"].Scope != types.ScopeProd || !byName["http"].Direct {
		t.Errorf("http: got %+v", byName["http"])
	}
	if byName["test"].Scope != types.ScopeDev || !byName["test"].Direct {
		t.Errorf("test: expected direct dev, got %+v", byName["test"])
	}
	if byName["meta"].Direct {
		t.Errorf("meta: expected transitive (not direct), got %+v", byName["meta"])
	}
}

func TestParsePubspecLockGraph_Modes(t *testing.T) {
	if g := ParsePubspecLockGraph(GraphInput{Lockfile: []byte(pubspecLockFixture), Mode: types.DependencyGraphOff}); len(g.Edges) != 0 {
		t.Errorf("off: expected 0 edges, got %d", len(g.Edges))
	}

	// direct: only "direct main"/"direct dev" packages.
	gd := ParsePubspecLockGraph(GraphInput{Lockfile: []byte(pubspecLockFixture), Mode: types.DependencyGraphDirect})
	got := map[string]string{}
	for _, e := range gd.Edges {
		if e.From != "." {
			t.Errorf("direct: expected from='.', got %q", e.From)
		}
		got[e.To] = e.Scope
	}
	if got["http@1.2.0"] != types.ScopeProd || got["test@1.24.9"] != types.ScopeDev {
		t.Errorf("direct: expected http(prod) + test(dev), got %v", got)
	}
	if _, ok := got["meta@1.11.0"]; ok {
		t.Error("direct: transitive meta must not appear")
	}

	// full: includes the transitive closure too.
	gf := ParsePubspecLockGraph(GraphInput{Lockfile: []byte(pubspecLockFixture), Mode: types.DependencyGraphFull})
	full := map[string]bool{}
	for _, e := range gf.Edges {
		full[e.To] = true
	}
	if !full["meta@1.11.0"] {
		t.Errorf("full: expected transitive meta, got %v", full)
	}
}
