package parsers

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/petrarca/tech-stack-analyzer/internal/types"
)

// These tests run the graph producers against REAL lockfiles generated by the
// actual package managers (cargo, npm, pnpm, uv, bundler, composer, mix,
// poetry) from well-known PUBLIC packages -- see testdata/lockfiles/. They
// verify the parsers handle authentic tool output (not just hand-written
// fixtures) and that the expected package-to-package edges are produced.
//
// The fixtures contain only public OSS packages (serde, express, requests,
// sinatra, monolog, flask, plug, ...). No proprietary or internal package
// names appear in them.

func readFixture(t *testing.T, name string) []byte {
	t.Helper()
	b, err := os.ReadFile(filepath.Join("testdata", "lockfiles", name))
	if err != nil {
		t.Fatalf("read fixture %s: %v", name, err)
	}
	return b
}

func edgeSetFromGraph(g LockGraph) map[string]bool {
	out := map[string]bool{}
	for _, e := range g.Edges {
		out[e.From+"->"+e.To] = true
	}
	return out
}

func assertEdges(t *testing.T, got map[string]bool, want ...string) {
	t.Helper()
	for _, w := range want {
		if !got[w] {
			t.Errorf("missing edge %q (have %d edges)", w, len(got))
		}
	}
}

func TestRealLockfile_Cargo(t *testing.T) {
	g := ParseCargoLockGraph(GraphInput{Lockfile: readFixture(t, "Cargo.lock"), Mode: types.DependencyGraphFull})
	got := edgeSetFromGraph(g)
	// serde feature=derive pulls in serde_derive; macro stack proc-macro2/quote/syn.
	assertEdges(t, got,
		"fixture@0.1.0->serde@1.0.228",
		"fixture@0.1.0->serde_json@1.0.150",
		"serde@1.0.228->serde_derive@1.0.228",
		"quote@1.0.45->proc-macro2@1.0.106",
	)
}

func TestRealLockfile_Pnpm(t *testing.T) {
	g := ParsePnpmLockGraph(GraphInput{Lockfile: readFixture(t, "pnpm-lock.yaml"), Mode: types.DependencyGraphFull})
	got := edgeSetFromGraph(g)
	// express 5.2.1 is the root dep; it pulls in router/vary/cookie-signature.
	assertEdges(t, got,
		"express@5.2.1->router@2.2.0",
		"express@5.2.1->vary@1.1.2",
		"express@5.2.1->cookie-signature@1.2.2",
	)
}

func TestRealLockfile_Uv(t *testing.T) {
	g := ParseUvLockGraph(GraphInput{Lockfile: readFixture(t, "uv.lock"), Mode: types.DependencyGraphFull})
	got := edgeSetFromGraph(g)
	// requests -> its classic transitive set.
	assertEdges(t, got,
		"requests@2.34.2->urllib3@2.7.0",
		"requests@2.34.2->certifi@2026.5.20",
		"requests@2.34.2->idna@3.18",
	)
}

func TestRealLockfile_Gemfile(t *testing.T) {
	g := ParseGemfileLockGraph(GraphInput{Lockfile: readFixture(t, "Gemfile.lock"), Mode: types.DependencyGraphFull})
	got := edgeSetFromGraph(g)
	assertEdges(t, got,
		"sinatra@4.2.1->rack@3.2.6",
		"sinatra@4.2.1->rack-protection@4.2.1",
		"rack-session@2.1.2->rack@3.2.6",
	)
}

func TestRealLockfile_Composer(t *testing.T) {
	g := ParseComposerLockGraph(GraphInput{Lockfile: readFixture(t, "composer.lock"), Mode: types.DependencyGraphFull})
	got := edgeSetFromGraph(g)
	assertEdges(t, got, "monolog/monolog@3.10.0->psr/log@3.0.2")
}

func TestRealLockfile_Mix(t *testing.T) {
	g := ParseMixLockGraph(GraphInput{Lockfile: readFixture(t, "mix.lock"), Mode: types.DependencyGraphFull})
	got := edgeSetFromGraph(g)
	assertEdges(t, got,
		"plug@1.19.2->mime@2.0.7",
		"plug@1.19.2->plug_crypto@2.1.1",
		"plug@1.19.2->telemetry@1.4.2",
	)
}

func TestRealLockfile_Poetry(t *testing.T) {
	g := ParsePoetryLockGraph(GraphInput{Lockfile: readFixture(t, "poetry.lock"), Mode: types.DependencyGraphFull})
	got := edgeSetFromGraph(g)
	assertEdges(t, got,
		"flask@3.1.3->jinja2@3.1.6",
		"flask@3.1.3->werkzeug@3.1.8",
		"flask@3.1.3->click@8.4.1",
		"click@8.4.1->colorama@0.4.6",
	)
}

func TestRealLockfile_NpmV3(t *testing.T) {
	g := ParsePackageLockGraph(GraphInput{Lockfile: readFixture(t, "package-lock.json"), Mode: types.DependencyGraphFull})
	got := edgeSetFromGraph(g)
	// express resolves transitives via node_modules nearest-wins.
	assertEdges(t, got,
		"express@5.2.1->router@2.2.0",
		"express@5.2.1->vary@1.1.2",
	)
}

// TestRealLockfile_AllParseWithoutPanic is a smoke test: every real fixture
// must parse in every mode without panicking and never emit a malformed node id.
func TestRealLockfile_AllModesNoMalformed(t *testing.T) {
	cases := []struct {
		file string
		fn   func(GraphInput) LockGraph
	}{
		{"Cargo.lock", ParseCargoLockGraph},
		{"package-lock.json", ParsePackageLockGraph},
		{"pnpm-lock.yaml", ParsePnpmLockGraph},
		{"uv.lock", ParseUvLockGraph},
		{"Gemfile.lock", ParseGemfileLockGraph},
		{"composer.lock", ParseComposerLockGraph},
		{"poetry.lock", ParsePoetryLockGraph},
		{"mix.lock", ParseMixLockGraph},
	}
	modes := []types.DependencyGraphMode{
		types.DependencyGraphOff, types.DependencyGraphDirect, types.DependencyGraphFull,
	}
	for _, c := range cases {
		content := readFixture(t, c.file)
		for _, m := range modes {
			g := c.fn(GraphInput{Lockfile: content, Mode: m})
			if m == types.DependencyGraphOff && len(g.Edges) != 0 {
				t.Errorf("%s off mode: expected 0 edges, got %d", c.file, len(g.Edges))
			}
			for _, e := range g.Edges {
				if e.From == "" || e.To == "" {
					t.Errorf("%s: empty edge endpoint %+v", c.file, e)
				}
				// 'to' must carry a version: "name@version" (1 '@') or a scoped
				// npm package "@scope/name@version" (2 '@'). 'from' may be '.'.
				if at := countAt(e.To); at < 1 || at > 2 {
					t.Errorf("%s: malformed 'to' node %q", c.file, e.To)
				}
			}
		}
	}
}

func countAt(s string) int {
	n := 0
	for _, r := range s {
		if r == '@' {
			n++
		}
	}
	return n
}
