package parsers

import (
	"testing"

	"github.com/petrarca/tech-stack-analyzer/internal/types"
)

const yarnLockGraphFixture = `# THIS IS AN AUTOGENERATED FILE.

express@^4.18.0:
  version "4.18.2"
  resolved "https://registry.yarnpkg.com/express/-/express-4.18.2.tgz"
  dependencies:
    accepts "~1.3.8"
    body-parser "1.20.1"

accepts@~1.3.8:
  version "1.3.8"
  resolved "https://registry.yarnpkg.com/accepts/-/accepts-1.3.8.tgz"

body-parser@1.20.1:
  version "1.20.1"
  resolved "https://registry.yarnpkg.com/body-parser/-/body-parser-1.20.1.tgz"
  dependencies:
    accepts "~1.3.8"
`

func TestParseYarnLockGraph_FullEdges(t *testing.T) {
	graph := ParseYarnLockGraph([]byte(yarnLockGraphFixture), types.DependencyGraphFull)

	got := map[string]bool{}
	for _, e := range graph.Edges {
		got[e.From+"->"+e.To] = true
	}
	for _, want := range []string{
		"express@4.18.2->accepts@1.3.8",
		"express@4.18.2->body-parser@1.20.1",
		"body-parser@1.20.1->accepts@1.3.8",
	} {
		if !got[want] {
			t.Errorf("missing edge %q; got %v", want, got)
		}
	}
}

func TestParseYarnLockGraph_Modes(t *testing.T) {
	if g := ParseYarnLockGraph([]byte(yarnLockGraphFixture), types.DependencyGraphOff); len(g.Edges) != 0 {
		t.Errorf("off mode: expected 0 edges, got %d", len(g.Edges))
	}

	// direct: express is the only entry not referenced as a dependency target.
	gd := ParseYarnLockGraph([]byte(yarnLockGraphFixture), types.DependencyGraphDirect)
	if len(gd.Edges) != 1 || gd.Edges[0].From != "." || gd.Edges[0].To != "express@4.18.2" {
		t.Errorf("direct mode: expected [. -> express@4.18.2], got %v", gd.Edges)
	}
}
