package parsers

import (
	"testing"

	"github.com/petrarca/tech-stack-analyzer/internal/types"
)

const yarnLockGraphFixture = `# THIS IS AN AUTOGENERATED FILE.

express@^4.18.0:
  version "4.18.2"
  resolved "https://registry.yarnpkg.com/express/-/express-4.18.2.tgz"
  dependencies:
    accepts "~1.3.8"
    body-parser "1.20.1"

accepts@~1.3.8:
  version "1.3.8"
  resolved "https://registry.yarnpkg.com/accepts/-/accepts-1.3.8.tgz"

body-parser@1.20.1:
  version "1.20.1"
  resolved "https://registry.yarnpkg.com/body-parser/-/body-parser-1.20.1.tgz"
  dependencies:
    accepts "~1.3.8"
`

func TestParseYarnLockGraph_FullEdges(t *testing.T) {
	graph := ParseYarnLockGraph(GraphInput{Lockfile: []byte(yarnLockGraphFixture), Mode: types.DependencyGraphFull})

	got := map[string]bool{}
	for _, e := range graph.Edges {
		got[e.From+"->"+e.To] = true
	}
	for _, want := range []string{
		"express@4.18.2->accepts@1.3.8",
		"express@4.18.2->body-parser@1.20.1",
		"body-parser@1.20.1->accepts@1.3.8",
	} {
		if !got[want] {
			t.Errorf("missing edge %q; got %v", want, got)
		}
	}
}

func TestParseYarnLockGraph_DirectFromManifest(t *testing.T) {
	// package.json declares express + accepts as direct. accepts is ALSO
	// transitive (express -> accepts); the manifest path must classify it
	// direct, which the not-referenced heuristic cannot.
	manifest := `{
  "dependencies": {
    "express": "^4.18.0",
    "accepts": "~1.3.8"
  }
}`
	gd := ParseYarnLockGraph(GraphInput{
		Lockfile: []byte(yarnLockGraphFixture),
		Manifest: []byte(manifest),
		Mode:     types.DependencyGraphDirect,
	})
	got := map[string]bool{}
	for _, e := range gd.Edges {
		if e.From != "." {
			t.Errorf("expected from='.', got %q", e.From)
		}
		got[e.To] = true
	}
	if !got["express@4.18.2"] || !got["accepts@1.3.8"] {
		t.Errorf("expected direct edges to express and accepts, got %v", got)
	}
	if got["body-parser@1.20.1"] {
		t.Error("body-parser is transitive only; must not be direct")
	}
}

// TestParseYarnLockGraph_OptionalDependencies verifies that optionalDependencies
// edges are traversed. These are real graph nodes (e.g. platform-specific native
// binaries pulled in via "os"/"cpu" gating) that SBOM consumers expect, since the
// install target is unknown at scan time. Fixture uses fictional package names.
func TestParseYarnLockGraph_OptionalDependencies(t *testing.T) {
	const fixture = `# THIS IS AN AUTOGENERATED FILE.

bundler@^1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/bundler/-/bundler-1.0.0.tgz"
  dependencies:
    helper "^1.0.0"
  optionalDependencies:
    bundler-linux-x64 "1.0.0"
    bundler-win32-x64 "1.0.0"

helper@^1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/helper/-/helper-1.0.0.tgz"

bundler-linux-x64@1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/bundler-linux-x64/-/bundler-linux-x64-1.0.0.tgz"

bundler-win32-x64@1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/bundler-win32-x64/-/bundler-win32-x64-1.0.0.tgz"
`
	graph := ParseYarnLockGraph(GraphInput{Lockfile: []byte(fixture), Mode: types.DependencyGraphFull})
	got := map[string]bool{}
	for _, e := range graph.Edges {
		got[e.From+"->"+e.To] = true
	}
	for _, want := range []string{
		"bundler@1.0.0->helper@1.0.0",
		"bundler@1.0.0->bundler-linux-x64@1.0.0",
		"bundler@1.0.0->bundler-win32-x64@1.0.0",
	} {
		if !got[want] {
			t.Errorf("missing edge %q; got %v", want, got)
		}
	}
}

func TestParseYarnLockGraph_Modes(t *testing.T) {
	if g := ParseYarnLockGraph(GraphInput{Lockfile: []byte(yarnLockGraphFixture), Mode: types.DependencyGraphOff}); len(g.Edges) != 0 {
		t.Errorf("off mode: expected 0 edges, got %d", len(g.Edges))
	}

	// direct: express is the only entry not referenced as a dependency target.
	gd := ParseYarnLockGraph(GraphInput{Lockfile: []byte(yarnLockGraphFixture), Mode: types.DependencyGraphDirect})
	if len(gd.Edges) != 1 || gd.Edges[0].From != "." || gd.Edges[0].To != "express@4.18.2" {
		t.Errorf("direct mode: expected [. -> express@4.18.2], got %v", gd.Edges)
	}
}
